# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# change these once we have a real hl7 URL
id: patientcorrections
canonical: https://keyes.dev/ig
version: 0.1.0
name: PatientCorrectionsImplementationGuide
title: "Patient Corrections Implementation Guide"
status: draft
publisher:
  - name: Patient Empowerment Workgroup
  - url: https://confluence.hl7.org/display/PE/Patient+Empowerment+Home
contact:
  - name: John Keyes
    telecom:
      - system: email
        value: john@johnkeyes.com
        use: work
description: The implementation guide for Patient Corrections.
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Specification: specification.html
  Artifacts Summary: artifacts.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
